# Generated by Django 5.1 on 2024-09-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_pedida',
            new_name='fecha_pedido',
        ),
    ]
